
Import data
```{r}
require(matrixTests)
require(matrixStats)
require(ggplot2)
require(patchwork)
require(dplyr)
require(data.table)
require(GeneCycle)
require(devtools)
require(ggh4x)
require(dplyr)
devtools::load_all("PowerCHORD")
# load data 
df = read.csv('data_analysis/GSE11923_series_matrix.txt',
              skip='65',header=F,sep='\t',row.names=1)
names(df)=paste0('CT',18:65)
df=df[!is.na(rowSds(as.matrix(df))>0),]
head(df)

# original osc genes 
orig_24 = read.csv2('data_analysis/pgen.1000442.s012.csv',sep=',')
orig_12 = read.csv2('data_analysis/pgen.1000442.s013.csv',sep=',')
orig_8  = read.csv2('data_analysis/pgen.1000442.s014.csv',sep=',')

# fisher g test
fg      = GeneCycle::fisher.g.test(t(as.matrix(df)))
q_gtest = p.adjust(fg,method='fdr')

```

# Cosinor on full dataset
```{r}
pers = c(8,12,24)
sdf = pers |> lapply(function(per){
  cs   =  matrixTests::row_cosinor(df,c(18:65),period = per) 
  qval = p.adjust(cs$pvalue,method='fdr')
  
  if (per==8){
    orig = orig_8
  }else if(per==12){
    orig = orig_12
  }else if(per==24){
    orig = orig_24
  }
  
  classif = rownames(df) %in% orig[,1] 
  pdf = data.frame(probe   = rownames(df),
                   q_osc   = qval,
                   classif = classif,
                   q_fish  = q_gtest,
                   per     = per
                   )
}) |> rbindlist() |> data.frame()


sdf |> filter(q_osc<.05 & q_fish <.05) |> 
  ggplot(aes(x=q_osc,y=q_fish,color=classif))+geom_point(size=1)+
  facet_wrap(~per,nrow=3)
```

# Sub-sampling 1
```{r}
# optimal meas times
mu_opt   = as.numeric(t(read.csv('data_analysis/mu_opt.txt',header=F))) 
mt_full  = c(18:65)
mt_opt   = mt_full[mu_opt>0]

# equispaced subsampling
mt_sub   = seq(18,65,6)
length(mt_sub)
length(mt_opt)

pars = expand.grid(sampling = c('full','sub','optimal'),
            per = c(8,12,24))

sdf = c(1:dim(pars)[1]) |> lapply(function(ind){
  samp = pars[ind,]$sampling 
  per  = pars[ind,]$per
  
  if (samp == 'full'){
    dfloc=df
    mtloc=c(18:65)
  }else if (samp == 'sub'){
    dfloc=df[,mt_full %in% mt_sub] 
    mtloc=mt_sub
  }else if (samp == 'optimal'){
    dfloc=df[,mt_full %in% mt_opt] 
    mtloc=mt_opt
  }
  cs   =  matrixTests::row_cosinor(dfloc,mtloc,period = per) 
  qval = p.adjust(cs$pvalue,method='fdr')
  pdf = data.frame(probe   = rownames(dfloc),
                   p_osc   = cs$pvalue,
                   q_osc   = qval,
                   acro = cs$acrophase,
                   per = per,
                   sampling=samp
                   )
}
) |> rbindlist() |> data.frame()

sdf |> filter(p_osc<.05) |>  ggplot(aes(x=2*pi*acro/per))+geom_histogram()+facet_grid(per~sampling,scales = 'free')+scale_y_continuous(trans='log2')
```

# Sub-sampling 2
```{r}
mu_opt   = as.numeric(t(read.csv('data_analysis/mu_opt22.txt',header=F))) 
mt_full  = c(18:65)
mt_opt   = mt_full[mu_opt>0]

mt_sub = 18+c(c(0:8),8+c(1:8)*2,24+c(1:5)*4)


sdf = c(1:dim(pars)[1]) |> lapply(function(ind){
  samp = pars[ind,]$sampling 
  per  = pars[ind,]$per
  
  if (samp == 'full'){
    dfloc=df
    mtloc=c(18:65)
  }else if (samp == 'sub'){
    dfloc=df[,mt_full %in% mt_sub] 
    mtloc=mt_sub
  }else if (samp == 'optimal'){
    dfloc=df[,mt_full %in% mt_opt] 
    mtloc=mt_opt
  }
  cs   =  matrixTests::row_cosinor(dfloc,mtloc,period = per) 
  qval = p.adjust(cs$pvalue,method='fdr')
  pdf = data.frame(probe   = rownames(dfloc),
                   p_osc   = cs$pvalue,
                   q_osc   = qval,
                   acro = cs$acrophase,
                   per = per,
                   sampling=samp
                   )
}
) |> rbindlist() |> data.frame()

sdf |> filter(p_osc<.05) |>  ggplot(aes(x=2*pi*acro/per))+geom_histogram()+facet_grid(per~sampling,scales = 'free')+scale_y_continuous(trans='log2')

```


```{r}
mu_opt   = as.numeric(t(read.csv('data_analysis/mu_opt16.txt',header=F))) 
mt_full  = c(18:65)
mt_opt   = mt_full[mu_opt>0]

mt_sub =  18+c(c(0:8)*2,16+c(1:7)*4)

sdf = c(1:dim(pars)[1]) |> lapply(function(ind){
  samp = pars[ind,]$sampling 
  per  = pars[ind,]$per
  
  if (samp == 'full'){
    dfloc=df
    mtloc=c(18:65)
  }else if (samp == 'sub'){
    dfloc=df[,mt_full %in% mt_sub] 
    mtloc=mt_sub
  }else if (samp == 'optimal'){
    dfloc=df[,mt_full %in% mt_opt] 
    mtloc=mt_opt
  }
  cs   =  matrixTests::row_cosinor(dfloc,mtloc,period = per) 
  qval = p.adjust(cs$pvalue,method='fdr')
  pdf = data.frame(probe   = rownames(dfloc),
                   p_osc   = cs$pvalue,
                   q_osc   = qval,
                   acro = cs$acrophase,
                   per = per,
                   sampling=samp
                   )
}
) |> rbindlist() |> data.frame()

sdf |> filter(p_osc<.05) |>  ggplot(aes(x=2*pi*acro/per))+geom_histogram()+facet_grid(per~sampling,scales = 'free')+scale_y_continuous(trans='log2')

```


```{r}
mu_opt   = as.numeric(t(read.csv('data_analysis/mu_opt18.txt',header=F))) 
mt_full  = c(18:65)
mt_opt   = mt_full[mu_opt>0]

mt_sub   = 18+c(c(0:8),8+c(1:9)*4)
mt_sub   = mt_sub
acros = seq(0,2*pi,length.out=2^6+1)
acros = acros[1:(length(acros)-1)]

pars = expand.grid(acro=acros,
                   per=c(8,12,24),sampling=c('full','optimal','sub')) 


pars2 = expand.grid(sampling = c('full','sub','optimal'),
            per = c(8,12,24))
sdf = c(1:dim(pars2)[1]) |> lapply(function(ind){

  samp = pars2[ind,]$sampling 
  per  = pars2[ind,]$per
  
  if (samp == 'full'){
    dfloc=df
    mtloc=c(18:65)
  }else if (samp == 'sub'){
    dfloc=df[,mt_full %in% mt_sub] 
    mtloc=mt_sub
  }else if (samp == 'optimal'){
    dfloc=df[,mt_full %in% mt_opt] 
    mtloc=mt_opt
  }
  cs   =  matrixTests::row_cosinor(dfloc,mtloc,period = per) 
  qval = p.adjust(cs$pvalue,method='fdr')
  pdf = data.frame(probe   = rownames(dfloc),
                   p_osc   = cs$pvalue,
                   q_osc   = qval,
                   acro = cs$acrophase,
                   amp = cs$amplitude,
                   per = per,
                   sampling=samp
                   )
}
) |> rbindlist() |> data.frame()

pars$power = c(1:dim(pars)[1]) |> lapply(function(ind){
  acro   = pars[ind,]$acro 
  per    = pars[ind,]$per
  sampling = pars[ind,]$sampling

  freq=NaN
  if (per==24){
    freq=2
  }else if (per==12){
    freq=4
  }else if (per==8){
    freq=6
  }
  if (sampling=='full'){
    mt=mt_full/48
  }else if(sampling=='optimal'){
    mt=mt_opt/48
  }else if(sampling=='sub'){
    mt=mt_sub/48
  }
 
 perloc = per 
 sloc   = sampling
 ahr    = acro*per/2/pi
 
 # mean of all genes with this design and period
 Agrp = sdf |> filter(per==perloc & sampling==sloc & (p_osc <.05)) |>
    pull(amp) |> unlist() |> mean() 
 
 # mean of all genes with similar acrophase
 dloc           = data.frame(v1=abs(sdf$acro-ahr)/sdf$per)
 dloc$v2        = 1-dloc$v1
 close_in_phase = rowMins(as.matrix(dloc))< .1
 Aacro = sdf |> filter(per==perloc & sampling==sloc& (p_osc <.05) & close_in_phase) |>
    pull(amp) |> unlist() |> mean()
  
  evalPower(mt,freq,acro,Amp=Aacro/Agrp)
  }
)
pars$power = as.numeric(pars$power)


pars$power_flat = c(1:dim(pars)[1]) |> lapply(function(ind){
  acro   = pars[ind,]$acro 
  per    = pars[ind,]$per
  sampling = pars[ind,]$sampling

  freq=NaN
  if (per==24){
    freq=2
  }else if (per==12){
    freq=4
  }else if (per==8){
    freq=6
  }
  if (sampling=='full'){
    mt=mt_full/48
  }else if(sampling=='optimal'){
    mt=mt_opt/48
  }else if(sampling=='sub'){
    mt=mt_sub/48
  }
 
 perloc = per 
 sloc   = sampling
 ahr    = acro*per/2/pi
  evalPower(mt,freq,acro,Amp=1)
 }
)
pars$power_flat = as.numeric(pars$power_flat)



sdf <- sdf |> 
  filter(p_osc < 0.05) |> 
  group_by(sampling, per) |> 
  mutate(
    bin_width = (max(2 * pi * acro / per) - min(2 * pi * acro / per)) / 30, # Default bins = 30
    bin = floor((2 * pi * acro / per - min(2 * pi * acro / per)) / bin_width), # Bin index
    max_count = max(table(bin), na.rm = TRUE) # Maximum count per bin
  ) |> 
  ungroup()
sdf <- sdf |> 
  group_by(per) |> 
  mutate(max_count = max(max_count, na.rm = TRUE)) |> 
  ungroup()
p=sdf |> 
  filter(p_osc < 0.05) |> 
  ggplot(aes(x = 2*pi*acro/per )) +
  geom_histogram(aes(y = ..count..)) +
  facet_grid2(per ~ sampling, scales = "free") + # Use ggh4x facet_grid2
  facetted_pos_scales(
    y = list(
      per == 8 ~ scale_y_continuous(sec.axis = sec_axis(~ . / max(sdf[sdf$per==8,]$max_count), name = "Power (linear scale)")),
      per == 12 ~ scale_y_continuous(sec.axis = sec_axis(~ . / max(sdf[sdf$per==12,]$max_count), name = "Power (linear scale)")),
      per == 24 ~ scale_y_continuous(sec.axis = sec_axis(~ . / max(sdf[sdf$per==24,]$max_count), name = "Power (linear scale)"))
    )
  )



source('PLOSfigures/clean_theme.R')
pmc = sdf[,c('per','max_count')] |> unique()
pars <- pars |> 
  left_join(pmc, by = "per") 
p1 = p +geom_line(data=pars,aes(x = acro, y = power*max_count),color='red')+
  geom_line(data=pars,aes(x = acro, y = power_flat*max_count),color='blue')+clean_theme()

p2 = sdf |> filter(p_osc<.05) |> ggplot(aes(x=acro*2*pi/per,y=amp))+geom_point(size=.5,alpha=.1)+facet_grid(per~sampling)+scale_y_continuous(trans='log2')+clean_theme()
```
```{r}
rbind(data.frame(time=mt_full,type='full'),
           data.frame(time=mt_sub,type='sub'),
           data.frame(time=mt_opt,type='optimal')) |> 
  ggplot(aes(x=time,y=1))+geom_point()+facet_wrap(~type,ncol=1)
```

# equispaced sub sampling wasn't as interesting